symfony-travelexpress/src/Entity/City.php
<?php

namespace App\Entity;

use App\Repository\CityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CityRepository::class)
 */
class City
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $city_name;

    /**
     * @ORM\OneToMany(targetEntity=Travel::class, mappedBy="drive_to")
     */
    private $travel;

    public function __construct()
    {
        $this->travel = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCityName(): ?string
    {
        return $this->city_name;
    }

    public function setCityName(string $city_name): self
    {
        $this->city_name = $city_name;

        return $this;
    }

    /**
     * @return Collection|Travel[]
     */
    public function getTravel(): Collection
    {
        return $this->travel;
    }

    public function addTravel(Travel $travel): self
    {
        if (!$this->travel->contains($travel)) {
            $this->travel[] = $travel;
            $travel->setDriveTo($this);
        }

        return $this;
    }

    public function removeTravel(Travel $travel): self
    {
        if ($this->travel->removeElement($travel)) {
            // set the owning side to null (unless already changed)
            if ($travel->getDriveTo() === $this) {
                $travel->setDriveTo(null);
            }
        }

        return $this;
    }
}

symfony-travelexpress/src/Entity/Travel.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\TravelRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TravelRepository::class)
 */
class Travel
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThanOrEqual("today")
     */
    private $departure_datetime;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *      min = 1,
     *      max = 60,
     *      notInRangeMessage = "You must have between {{ min }} and {{ max }} seats available",
     * )
     */
    private $seat_available;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="purpose_travel")
     * @ORM\JoinColumn(nullable=true)
     */
    private $user_driver;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="is_passenger")
     */
    private $user_passenger;

    /**
     * @ORM\ManyToOne(targetEntity=Profile::class, inversedBy="set_preference")
     * @ORM\JoinColumn(nullable=true)
     */
    private $profile;

    /**
     * @ORM\ManyToOne(targetEntity=City::class, inversedBy="travel")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank
     */
    private $drive_to;

    /**
     * @ORM\ManyToOne(targetEntity=City::class, inversedBy="travel")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank
     */
    private $drive_from;

    public function __construct()
    {
        $this->user_passenger = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDepartureDatetime(): ?\DateTimeInterface
    {
        return $this->departure_datetime;
    }

    public function setDepartureDatetime(\DateTimeInterface $departure_datetime): self
    {
        $this->departure_datetime = $departure_datetime;

        return $this;
    }

    public function getSeatAvailable(): ?int
    {
        return $this->seat_available;
    }

    public function setSeatAvailable(int $seat_available): self
    {
        $this->seat_available = $seat_available;

        return $this;
    }

    public function getUserDriver(): ?User
    {
        return $this->user_driver;
    }

    public function setUserDriver(?User $user_driver): self
    {
        $this->user_driver = $user_driver;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUserPassenger(): Collection
    {
        return $this->user_passenger;
    }

    public function addUserPassenger(User $userPassenger): self
    {
        if (!$this->user_passenger->contains($userPassenger)) {
            $this->user_passenger[] = $userPassenger;
            $userPassenger->addIsPassenger($this);
        }

        return $this;
    }

    public function removeUserPassenger(User $userPassenger): self
    {
        if ($this->user_passenger->removeElement($userPassenger)) {
            $userPassenger->removeIsPassenger($this);
        }

        return $this;
    }

    public function getProfile(): ?Profile
    {
        return $this->profile;
    }

    public function setProfile(?Profile $profile): self
    {
        $this->profile = $profile;

        return $this;
    }

    public function getCar(): ?Car
    {
        return $this->car;
    }

    public function setCar(?Car $car): self
    {
        $this->car = $car;

        return $this;
    }

    public function getDriveTo(): ?City
    {
        return $this->drive_to;
    }

    public function setDriveTo(?City $drive_to): self
    {
        $this->drive_to = $drive_to;

        return $this;
    }

    public function getDriveFrom(): ?City
    {
        return $this->drive_from;
    }

    public function setDriveFrom(?City $drive_from): self
    {
        $this->drive_from = $drive_from;

        return $this;
    }
}

symfony-travelexpress/src/Form/SearchType.php
<?php

namespace App\Form;

use App\Entity\City;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class SearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('departure', EntityType::class,
                [
                    'class' => City::class,
                    'choice_label' => 'city_name',
                    'placeholder' => 'Ville de départ',
                    'attr' => [
                        'class' => 'mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm',
                    ]
                ])
            ->add('arrival', EntityType::class,
                [
                    'class' => City::class,
                    'choice_label' => 'city_name',
                    'placeholder' => 'Ville d\'arrivée',
                    'attr' => [
                        'class' => 'mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm',
                    ]
                ])
        ;
    }
}

symfony-travelexpress/src/Controller/SearchController.php
<?php

namespace App\Controller;

use App\Entity\Profile;
use App\Entity\Travel;

use App\Form\SearchType;
use App\Form\NewTravelType;
use App\Form\CheckoutType;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SearchController extends AbstractController
{
    private $requestStack;

    public function __construct(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }

    /**
     * @Route("/", name="search")
     */
    public function index(Request $request): Response
    {
        // Getting session
        $session = $this->requestStack->getSession();
        $connected_session = $session->get('connected');

        // Making front-end form
        $form = $this->createForm(SearchType::class, array('method' => 'GET'));
        $form->handleRequest($request);
        // Getting available travel
        $travels = $this->getDoctrine()
            ->getRepository(Travel::class)
            ->findAvailable()
        ;

        if ($connected_session == "true") {
            $user_id = $session->get('user_id');
        } else $user_id = null;

        // Form sent statement
        if ($form->isSubmitted() && $form->isValid()) {
            $travels = $this->getDoctrine()
                ->getRepository(Travel::class)
                ->findByDepartureAndArrival($form->get('departure')->getData(), $form->get('arrival')->getData())
            ;
        }
        // Rendering
        return $this->render('search/index.html.twig', [
            'travels' => $travels,
            'search_form' => $form->createView(),
            'user_id' => $user_id,
        ]);
    }

    /**
     * @Route("/travel/new", name="newTravel")
     */
    public function newTravel(Request $request): Response
    {
        // Getting session
        $session = $this->requestStack->getSession();
        $connected_session = $session->get('connected');
        // User logged statement
        if ($connected_session == "true")
        {
            // Making front-end form
            $travel = new Travel();
            $form = $this->createForm(NewTravelType::class, $travel);
            $form->handleRequest($request);
            $user_id = $session->get('user_id');

            // Form sent statement
            if ($form->isSubmitted() && $form->isValid()) {
                // Adding new travel entry to database
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($travel);
                $entityManager->flush();
                // Setting user id for new travel entry
                $user_id = $session->get('user_id');
                $travel_id = $form->getData()->getId();
                $initUserQuery = "UPDATE travel SET user_driver_id = :user_id, profile_id = :user_id WHERE id = :travel_id";
                $statement = $entityManager->getConnection()->prepare($initUserQuery);
                $statement->bindValue('user_id', $user_id);
                $statement->bindValue('travel_id', $travel_id);
                $statement->execute();

                // Redirecting
                return $this->redirectToRoute('search');
            }
            // Form isn't sent statement
            else {
                return $this->render('search/new.html.twig', [
                    'travel' => $travel,
                    'new_travel_form' => $form->createView(),
                    'user_id' => $user_id,
                ]);
            }
        }
        // User doesn't logged statement
        else
        {
            // Redirecting to log in page
            return $this->redirectToRoute('login');
        }
    }

    /**
     * @Route("/travel", name="travel")
     */
    public function travel(): Response
    {
        // Getting session
        $session = $this->requestStack->getSession();
        $connected_session = $session->get('connected');

        if ($connected_session == "true") {
            $user_id = $session->get('user_id');
        } else $user_id = null;

        $travels = $this->getDoctrine()
            ->getRepository(Travel::class)
            ->findAvailable()
        ;

        return $this->render('search/travel.html.twig', [
            'listtravel' => $travels,
            'user_id' => $user_id,
        ]);
    }

    /**
     * @Route("/book/{id}", name="book")
     */
    public function book($id, Request $request): Response
    {
        // Getting session
        $session = $this->requestStack->getSession();
        $connected_session = $session->get('connected');
        // User logged statement
        if ($connected_session == "true")
        {
            // Making front-end form
            $checkout_form = $this->createForm(CheckoutType::class);
            $checkout_form->handleRequest($request);
            $user_id = $session->get('user_id');
            // Getting travel information in database
            $travel = $this->getDoctrine()
                ->getRepository(Travel::class)
                ->find($id);
            if($checkout_form->isSubmitted() && $checkout_form->isValid())
            {
                $seat_available = $travel->getSeatAvailable();
                $seat_wanted = $checkout_form->get('seat_wanted')->getData();
                // Enough seat available statement
                if ($seat_wanted <= $seat_available)
                {
                    return $this->redirectToRoute('checkout',[
                        'id' => $id,
                        'seat_wanted' => $seat_wanted,
                    ]);
                }
                else
                {
                    return $this->render('search/book.html.twig', [
                        'travel' => $travel,
                        'checkout_form' => $checkout_form->createView(),
                        'error' => 1,
                        'user_id' => $user_id,
                    ]);
                }
            }
            // Rendering
            return $this->render('search/book.html.twig', [
                'travel' => $travel,
                'checkout_form' => $checkout_form->createView(),
                'error' => 0,
                'user_id' => $user_id,
            ]);
        }
        // User doesn't logged statement
        else
        {
            // Redirecting to log in page
            return $this->redirectToRoute('login');
        }
    }

    /**
     * @Route("/checkout/{id}/{seat_wanted}", name="checkout")
     */
    public function checkout($id, $seat_wanted)
    {
        // Getting session
        $session = $this->requestStack->getSession();
        $connected_session = $session->get('connected');
        // User logged statement
        if ($connected_session == "true")
        {
            // Getting travel information in database
            $travel = $this->getDoctrine()
                ->getRepository(Travel::class)
                ->find($id);
            // Getting seat available value of travel
            $seat_available = $travel->getSeatAvailable();
            $user_id = $session->get('user_id');
            // Available seat statement
            if ($seat_wanted <= $seat_available)
            {
                // Decrementing travel available place in database
                $new_seat_available = $seat_available - $seat_wanted;
                $decrementSeatAvailableQuery = "UPDATE travel SET seat_available = :new_seat_available WHERE id = :travel_id";
                $entityManager = $this->getDoctrine()->getManager();
                $statement = $entityManager->getConnection()->prepare($decrementSeatAvailableQuery);
                $statement->bindValue('new_seat_available', $new_seat_available);
                $statement->bindValue('travel_id', $id);
                $statement->execute();
                //Rendering
                return $this->render('search/checkout.html.twig', [
                    'travel' => $travel,
                    'seat_wanted' => $seat_wanted,
                    'error' => 0,
                    'user_id' => $user_id,
                ]);
            }
            // Seat no longer available statement
            else
            {
                return $this->render('search/checkout.html.twig', [
                    'travel' => $travel,
                    'seat_wanted' => $seat_wanted,
                    'error' => 1,
                    'user_id' => $user_id,
                ]);
            }
        }
        // User doesn't logged statement
        else
        {
            // Redirecting to log in page
            return $this->redirectToRoute('login');
        }
    }
}

symfony-travelexpress/templates/search/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}TravelExpress - Choisir votre trajet{% endblock %}

{% block body %}
    <div class="min-h-full flex items-center justify-center py-12 px-4">
        <div class="max-w-md w-full space-y-8">
            <div>
                <h2 class="mt-6 text-center text-3xl font-bold text-gray-900">
                    Récapitulatif de la réservation
                </h2>
            </div>
            <div>
                <div>
                    Vous partez de <a class="font-semibold">{{ travel.driveFrom.cityName }}</a> et arrivez à
                    <a class="font-semibold">{{ travel.driveTo.cityName }}</a>,
                    le <a class="font-semibold">{{ travel.departureDatetime | date('d/m/Y')}}</a> à <a class="font-semibold">{{ travel.departureDatetime | date('H:i')}}.</a>
                </div>
                <div>
                    Votre conducteur est <a class="font-semibold">{{ travel.userDriver.name }} {{ travel.userDriver.surname }}</a>.
                </div>
                <div>
                    Ce conducteur accepte :
                    {%if travel.profile.animal %}
                        <svg class="h-5 w-5 inline text-blue-600 svg-inline--fa fa-paw fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M256 224c-79.41 0-192 122.76-192 200.25 0 34.9 26.81 55.75 71.74 55.75 48.84 0 81.09-25.08 120.26-25.08 39.51 0 71.85 25.08 120.26 25.08 44.93 0 71.74-20.85 71.74-55.75C448 346.76 335.41 224 256 224zm-147.28-12.61c-10.4-34.65-42.44-57.09-71.56-50.13-29.12 6.96-44.29 40.69-33.89 75.34 10.4 34.65 42.44 57.09 71.56 50.13 29.12-6.96 44.29-40.69 33.89-75.34zm84.72-20.78c30.94-8.14 46.42-49.94 34.58-93.36s-46.52-72.01-77.46-63.87-46.42 49.94-34.58 93.36c11.84 43.42 46.53 72.02 77.46 63.87zm281.39-29.34c-29.12-6.96-61.15 15.48-71.56 50.13-10.4 34.65 4.77 68.38 33.89 75.34 29.12 6.96 61.15-15.48 71.56-50.13 10.4-34.65-4.77-68.38-33.89-75.34zm-156.27 29.34c30.94 8.14 65.62-20.45 77.46-63.87 11.84-43.42-3.64-85.21-34.58-93.36s-65.62 20.45-77.46 63.87c-11.84 43.42 3.64 85.22 34.58 93.36z"></path></svg>
                    {%else%}
                        <svg class="h-5 w-5 inline text-red-600 svg-inline--fa fa-paw fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M256 224c-79.41 0-192 122.76-192 200.25 0 34.9 26.81 55.75 71.74 55.75 48.84 0 81.09-25.08 120.26-25.08 39.51 0 71.85 25.08 120.26 25.08 44.93 0 71.74-20.85 71.74-55.75C448 346.76 335.41 224 256 224zm-147.28-12.61c-10.4-34.65-42.44-57.09-71.56-50.13-29.12 6.96-44.29 40.69-33.89 75.34 10.4 34.65 42.44 57.09 71.56 50.13 29.12-6.96 44.29-40.69 33.89-75.34zm84.72-20.78c30.94-8.14 46.42-49.94 34.58-93.36s-46.52-72.01-77.46-63.87-46.42 49.94-34.58 93.36c11.84 43.42 46.53 72.02 77.46 63.87zm281.39-29.34c-29.12-6.96-61.15 15.48-71.56 50.13-10.4 34.65 4.77 68.38 33.89 75.34 29.12 6.96 61.15-15.48 71.56-50.13 10.4-34.65-4.77-68.38-33.89-75.34zm-156.27 29.34c30.94 8.14 65.62-20.45 77.46-63.87 11.84-43.42-3.64-85.21-34.58-93.36s-65.62 20.45-77.46 63.87c-11.84 43.42 3.64 85.22 34.58 93.36z"></path></svg>
                    {%endif%}
                    {%if travel.profile.smoke %}
                        <svg class="h-5 w-5 inline text-blue-600 svg-inline--fa fa-smoking fa-w-20" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><path fill="currentColor" d="M632 352h-48c-4.4 0-8 3.6-8 8v144c0 4.4 3.6 8 8 8h48c4.4 0 8-3.6 8-8V360c0-4.4-3.6-8-8-8zM553.3 87.1c-5.7-3.8-9.3-10-9.3-16.8V8c0-4.4-3.6-8-8-8h-48c-4.4 0-8 3.6-8 8v62.3c0 22 10.2 43.4 28.6 55.4 42.2 27.3 67.4 73.8 67.4 124V280c0 4.4 3.6 8 8 8h48c4.4 0 8-3.6 8-8v-30.3c0-65.5-32.4-126.2-86.7-162.6zM432 352H48c-26.5 0-48 21.5-48 48v64c0 26.5 21.5 48 48 48h384c8.8 0 16-7.2 16-16V368c0-8.8-7.2-16-16-16zm-32 112H224v-64h176v64zm87.7-322.4C463.8 125 448 99.3 448 70.3V8c0-4.4-3.6-8-8-8h-48c-4.4 0-8 3.6-8 8v66.4c0 43.7 24.6 81.6 60.3 106.7 22.4 15.7 35.7 41.2 35.7 68.6V280c0 4.4 3.6 8 8 8h48c4.4 0 8-3.6 8-8v-30.3c0-43.3-21-83.4-56.3-108.1zM536 352h-48c-4.4 0-8 3.6-8 8v144c0 4.4 3.6 8 8 8h48c4.4 0 8-3.6 8-8V360c0-4.4-3.6-8-8-8z"></path></svg>
                    {%else%}
                        <svg class="h-5 w-5 inline text-red-600 svg-inline--fa fa-smoking-ban fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M96 304c0 8.8 7.2 16 16 16h117.5l-96-96H112c-8.8 0-16 7.2-16 16v64zM256 0C114.6 0 0 114.6 0 256s114.6 256 256 256 256-114.6 256-256S397.4 0 256 0zm0 448c-105.9 0-192-86.1-192-192 0-41.4 13.3-79.7 35.7-111.1l267.4 267.4C335.7 434.7 297.4 448 256 448zm45.2-192H384v32h-50.8l-32-32zm111.1 111.1L365.2 320H400c8.8 0 16-7.2 16-16v-64c0-8.8-7.2-16-16-16H269.2L144.9 99.7C176.3 77.3 214.6 64 256 64c105.9 0 192 86.1 192 192 0 41.4-13.3 79.7-35.7 111.1zM320.6 128c-15.6 0-28.6-11.2-31.4-25.9-.7-3.6-4-6.1-7.7-6.1h-16.2c-5 0-8.7 4.5-8 9.4 4.6 30.9 31.2 54.6 63.3 54.6 15.6 0 28.6 11.2 31.4 25.9.7 3.6 4 6.1 7.7 6.1h16.2c5 0 8.7-4.5 8-9.4-4.6-30.9-31.2-54.6-63.3-54.6z"></path></svg
                    {%endif%}
                </div>
                <form class="mt-8 space-y-6" action="#" method="POST">
                    {{ form_start(checkout_form) }}
                    <input type="hidden" name="remember" value="true">
                    <div class="rounded-md -space-y-px">
                        Veuillez choisir le nombre de places à réserver :
                        <p class="text-sm">
                            ({{ travel.seatAvailable }} places restantes)
                        </p>
                        <div class="text-md font-semibold text-gray-900">
                            {{ form_widget(checkout_form.seat_wanted) }}
                        </div>
                    </div>
                    {% if error == 1 %}
                        <div class="text-red-600 font-base font-normal mb-2">
                            <p>
                                <svg xmlns="http://www.w3.org/2000/svg" class="inline h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                                Vous ne pouvez pas réserver plus de {{ travel.seatAvailable }} places.
                            </p>
                        </div>
                    {% endif %}
                    <div>
                        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700">
                            {{ button_label|default('Procéder au payement') }}
                        </button>
                    </div>
                    {{ form_end(checkout_form) }}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

symfony-travelexpress/templates/search/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}TravelExpress - Nouveau trajet{% endblock %}

{% block body %}
    <div class="min-h-full flex items-center justify-center py-12 px-4">
        <div class="max-w-md w-full space-y-8">
            <div>
                <img class="mx-auto h-12 w-auto" src="{{ asset('logotravelexpress.png') }}" alt="Logo TravelExpress">
                <h2 class="mt-6 text-center text-3xl font-bold text-gray-900">
                    Créer un trajet
                </h2>
                <p class="mt-2 text-center text-sm text-gray-600">
                    Ou
                    <a href="/search" class="font-medium text-blue-600 hover:text-blue-500">
                        recherchez en un maintenant
                    </a>
                </p>
            </div>
            <form class="mt-8 space-y-6" action="#" method="POST">
                {{ form_start(new_travel_form) }}
                <input type="hidden" name="remember" value="true">
                <div>
                    <div class="mb-3 text-md font-semibold text-gray-900">Ville de départ
                        {{ form_widget(new_travel_form.drive_from) }}
                    </div>
                    <div class="pb-3 text-md font-semibold text-gray-900">Ville d'arrivée
                        {{ form_widget(new_travel_form.drive_to) }}
                    </div>
                    <div class="pb-3 text-md font-semibold text-gray-900">Date de départ
                        {{ form_widget(new_travel_form.departure_datetime) }}
                    </div>
{#                    <div class="pb-3 text-md font-semibold text-gray-900">Voiture utilisée#}
{#                        {{ form_widget(new_travel_form.car) }}#}
{#                    </div>#}
                    <div class="pb-3 text-md font-semibold text-gray-900">Places disponibles
                        {{ form_widget(new_travel_form.seat_available) }}
                    </div>
                    {#                    <div class="pb-3 text-md font-semibold text-gray-900">Conducteur#}
{#                        {{ form_widget(new_travel_form.user_driver) }}#}
{#                    </div>#}
{#                    <div class="text-md font-semibold text-gray-900">Profile#}
{#                        {{ form_widget(new_travel_form.profile) }}#}
{#                    </div>#}
                </div>
                <div>
                    <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700">
                        {{ button_label|default('Ajouter') }}
                    </button>
                </div>
                {{ form_end(new_travel_form) }}
            </form>
        </div>
    </div>
{% endblock %}